### ISSUE TITLE
8.0 > version requirement

### ISSUE THREAD

**Issue by linuxenko** [mbbill/vim-seattle#2]
I like this color schema, but it requires > 8.0 version of vim, is it too much difficult port `vim-seatle` for lesser versions of vim ?
thank you

btw . i've changed the 

```
if v:version < 800
```

version to `700` and it works just fine with my 7.4  . Idk, it were wrong decission ?

**Comment by mbbill** [comment]
you're right, it's a mistake to require vim>=8.0 for simply using this scheme. vim 8.0 is required only when you need to preview or customize it with its internal functions which used some vim8.0 features like json_decode() or map().
I've pushed a fix for it 80d60a4b1422c3550bff587ac26cdff00fda7c45
Thanks for reporting this!

**Comment by linuxenko** [comment]
Aha, cool !
